pull_request_rules:

  # If there is at least one positive review and CI passed, merge
  - name: Automatic merge on CI success and review
    conditions:
      - status-success=buddy/pipeline/Build & Test
      - "#approved-reviews-by>=1"
      - base=master
    actions:
      merge:
        method: squash

  # Delete branch after automatic merge
  - name: Delete branch after merge
    conditions: []
    actions:
      delete_head_branch: {}

  # Automatically merge Dependabot Pull Requests
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - status-success=buddy/pipeline/Build & Test
      - base=master
    actions:
      merge:
        method: merge

  # Remove outdated reviews
  - name: remove outdated reviews
    conditions:
      - base=master
    actions:
      dismiss_reviews:
        approved: True
        changes_requested: True